# NumPy & Series 문제


# 문제 1. 
- 답지를 확인하고 알맞게 슬라이싱을 진행하세요. 

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

In [12]:
arr[[1,3]]

array([2, 4])

In [1]:
# 답지
[2, 4]

[2, 4]

# 문제 2. 다차원 배열에서 슬라이싱

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [34]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [4]:
# 답지
# [[2, 3], [5, 6]]

# 문제 3. 배열에서 슬라이싱과 조건 사용

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [38]:
arr[3:7]

array([4, 5, 6])

In [5]:
# 답지
# [4, 5, 6]

# 문제 4. 배열의 일부 값 변경
- 두 번째와 세 번째 값을 10과 20으로 변경: [1, 10, 20, 4, 5]

In [39]:
arr = np.array([1, 2, 3, 4, 5])

In [44]:
arr[1:3] = [10, 20]
arr

array([ 1, 10, 20,  4,  5])

In [15]:
# 답지

array([ 1, 10, 20,  4,  5])

# 문제 5. 다차원 배열의 축 기준으로 슬라이싱
- 모든 행의 두번째 열 선택

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [53]:
arr[:,1]

array([2, 5, 8])

In [ ]:
# 답지
# [2, 5, 8]

# 문제 6. 복합 조건(여러 조건)을 사용
- 2보다 크고 5보다 작은 값 조회

In [74]:
arr = np.array([1, 2, 3, 4, 5])
filtered_arr = arr[(arr > 2) & (arr < 5)]

In [83]:
filtered_arr


array([3, 4])

In [8]:
# 2보다 크고 5보다 작은 값

# 답지
[3, 4]

[3, 4]

# 문제 7. 다차원 배열에 조건 적용
- 4보다 큰 값은 그대로, 나머지는 0으로 대체

In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.where(arr > 4, arr, 0) 

In [69]:
arr[:] = result
arr

array([[0, 0, 0],
       [0, 5, 6],
       [7, 8, 9]])

In [15]:
# 답지
[[0, 0, 0], [0, 5, 6], [7, 8, 9]]

[[0, 0, 0], [0, 5, 6], [7, 8, 9]]

# 문제 8. series에 numpy 적용1
- 주어진 Series에서 값이 50보다 큰 경우에는 1로, 그렇지 않은 경우에는 0으로 변경하시오.
- numpy 메서드 이용 (numpy.where)

In [84]:
import pandas as pd
import numpy as np

# Pandas Series 생성
series = pd.Series([10, 55, 30, 70, 45])

In [85]:
series_up = np.where(series > 50, 1, 0)
series_up

array([0, 1, 0, 1, 0])

In [14]:
# 답지
# 결과 출력
# [0 1 0 1 0] <class 'numpy.ndarray'>

# 문제 9. series에 numpy 적용2
- 주어진 Series에서 값이 30보다 크고 60보다 작은 경우에는 해당 값에 10을 더하고, 그 외의 값은 그대로 두시오.
- numpy 메서드 이용 (numpy.where)

In [86]:
# Pandas Series 생성
series = pd.Series([25, 35, 45, 60, 75])

In [87]:
series_p = np.where((series > 30) & (series < 60) , series + 10, series)
series_p

array([25, 45, 55, 60, 75])

In [18]:
# Series 결과 답안
result_series = pd.Series([25, 45, 55, 60, 75])

# 결과 출력
print(result_series)

0    25
1    45
2    55
3    60
4    75
dtype: int64


# 문제 10. 다중 조건
- 주어진 Series에서 cond 리스트에 조건을 정의하고, 각 조건을 만족하는 값에 대해 다른 연산을 수행하여 새로운 Series를 생성하시오.
    + cond[0]: 값이 50보다 크면 해당 값을 2배로 증가시킴.
    + cond[1]: 값이 30보다 작으면 해당 값을 10으로 변경.
    + 그 외의 값은 그대로 유지.

In [19]:
series = pd.Series([25, 45, 55, 60, 75])

SyntaxError: invalid syntax (4141724971.py, line 1)

In [20]:
# 결과 답안
pd.Series([10, 45, 110, 120, 150])

0     10
1     45
2    110
3    120
4    150
dtype: int64