# 라이브러리 설치

In [2]:
!pip install numpy  # 터미널에서 라이브러리 설치하는 방법 ! 붙이기

In [3]:
import numpy as np # 사용하기 위해 저장소에서 꺼내는 역할 import 

print(np.__version__)

2.1.1


In [5]:
# help(np)

In [6]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]
#      [5, 7, 9]

num1 + num2


[1, 2, 3, 4, 5, 6]

In [354]:
num1_arr = np.array(num1) # 기본 numpy 배열 만드는 법
num2_arr = np.array(num2)

num1_arr + num2_arr

array([5, 7, 9])

In [9]:
print(type(num1_arr))
# 속성, 메서드

<class 'numpy.ndarray'>


In [352]:
num1_arr.shape # 배열 모양

(3,)

In [351]:
num1_arr.ndim # 배열의 차원 수 

1

In [19]:
num1_arr.max(axis=0)
print(num1_arr.min(axis=0))

1


In [353]:
num1_arr = np.array(num1, dtype="int8")
num1_arr.dtype # 데이터 타입

dtype('int8')

### 배열 만드는 방법

In [356]:
# 기본적으로 다른 데이터 자료형을 numpy 배열로 변환
# 배열 생성
print(np.zeros(3))
print(np.zeros((3,3))) # 튜플형식으로 () 추가해서 행열 조합 가능
print(np.ones(3)) # 1로 된 numpy 배열 생성

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]


In [360]:
arr = np.ndarray(shape=(2,2,2), dtype=float, order="F") # ndarray는 이전에 가져온 값을 초기화 하지 않음
#기본 array는 array 뒤에 초기화 시키는 값이 입력되어 있음. shape 은 2*2*2 3차원, order "F"는 열우선 저장, 기본 "C"는 행우선 저장 용도는 확인 필요
arr.shape
arr

array([[ 5., 15.],
       [10., 20.]])

In [30]:
temp_arr = np.arange(16) # 16개 숫자 배열 만듦 1* 16
temp_arr.reshape(4,4) # 16개를 4*4로 재배열

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
a16 = np.array([1.333333], dtype=np.float16) # 비트 차이에 따라 입력 값 차이 발생해서 통일 시키거나, 정형화 하는 것 중요
a32 = np.array([1.333333], dtype=np.float32)

print(a16)
print(a32)

[1.333]
[1.333333]


In [32]:
print(a16*a32)

[1.7773433]


In [359]:
arr = np.array([-1, -2, -3])
arr/0

C:\Users\campus3S002\AppData\Local\Temp\ipykernel_1448\3259108307.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf, -inf, -inf])

결측치
- Missing Value
- nan : Not a Number, --> 아직 정의 되지 않은 숫자 의미

In [36]:
print(np.nan, type(np.nan))

nan <class 'float'>


In [37]:
print(np.inf, type(np.inf))

inf <class 'float'>


In [38]:
arr = np.array([-1, -2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


# 인덱싱 & 슬라이싱

In [39]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
arr[0][2]

np.int64(2)

In [48]:
arr = np.arange(10000).reshape(100, 100)
arr[0:4][0:1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [50]:
arr = np.arange(4)
arr[:2]

array([0, 1])

In [69]:
arr = np.arange(20).reshape(4,5)
arr[1:4, 2:5] # arr[행, 열]
arr[:, :] # 전체 데터터

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

# numpy broadcating 연산
- 리스트 배열이 달라도 맞춰서 연산 해주는 기능
- 
  `ex) [3*3] * 3 가능
      [3*3] + 1 가능


In [82]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
a + b

array([2, 4, 6])

In [83]:
a = np.array([1, 2, 3])
b = 3.0
a + b

array([4., 5., 6.])

## 조건 연산
- 원하는 결과값 : True/False


In [88]:
arr = np.array([10, 20, 30]) # True 값만 가져온다 -> 필터
arr > 10

array([False,  True,  True])

In [86]:
arr = np.array([10, 20, 30])
cond = [False, True, True]

arr[cond]

array([20, 30])

In [87]:
arr = np.array([18, 20, 50, 30, 16])
cond = arr > 18

arr[cond]

array([20, 50, 30])

In [89]:
arr = np.array([18, 20, 50, 30, 16])

arr[arr > 18]

array([20, 50, 30])

In [99]:
arr = np.array([18, 20, 50, 30, 16, 65, 70]) # 다중조건
con0 = arr > 18
con1 = arr < 65

arr[con0 | con1], arr[con0 & con1] # or, and

(array([18, 20, 50, 30, 16, 65, 70]), array([20, 50, 30]))

In [101]:
# 괄호로 감싸는 것 권장사항, 이유 : pandas 다중조건 필터링할 때는 아래 방법으로만 가능
# () 반드시 필요
arr[(con0 | con1)] 

array([18, 20, 50, 30, 16, 65, 70])

## np.where
- 조건문이라고 생각

In [103]:
import numpy as np
a = np.arange(10)
a
np.where(a < 5, a, 10*a) # where(조건, 반환값, else 반환값)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# 함수와 메서드

In [107]:
arr = np.arange(8).reshape(4, 2)
arr.sum(), arr

(np.int64(28),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]))

In [108]:
arr.sum(axis = 0) #세로축 합, 열단위 합
arr.sum(axis = 1) # 가로축 합, 행단위 합

(array([12, 16]), array([ 1,  5,  9, 13]))

In [168]:
# 무작위 랜덤 함수 만들기
np.random.seed(42) # 머신러닝 할 때, 이 코드를 자주 사용. 값이 고정 됨 
np.random.randint(10)

6

In [169]:
np.random.randint(46, size=6) # 0~ 45까지 무작위로 6개 가져오겠음

array([28, 14, 42,  7, 20, 38], dtype=int32)

In [167]:
np.random.randint(1, 46, size=(3, 4))# 1~ 45까지 무작위로 (3,4)로 가져오겠음

array([[20, 24, 33, 24],
       [11,  8, 36, 38],
       [40, 20, 35, 25]], dtype=int32)

In [165]:
x = np.linspace(0, 100, 11) # 0~ 100까지 11개로 분할 
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


# Pandas Series
- 1차원 배열

In [171]:
import pandas as pd
pd.__version__

'2.2.3'

In [194]:
data = [10, 20, 30]
s = pd.Series(data) # 시리즈는 행만 있는 1차원 배열
s

0    10
1    20
2    30
dtype: int64

In [173]:
type(s)

pandas.core.series.Series

In [196]:
import numpy as np

data = np.arange(5) # numpy를 series 로 변환 할 수 있음 
s = pd.Series(data)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [195]:
import numpy as np

data = np.arange(5)
s = pd.DataFrame(data) # DF는 행열이 있는 2차원 배열
s

0
0  0
1  1
2  2
3  3
4  4

In [176]:
data = ["시가", "고가",]
s = pd.Series(data)
s

0    시가
1    고가
dtype: object

In [177]:
data = [80000, "90000",]
s = pd.Series(data) # ㅐobject, category 등 속성 살펴보는 것도 중요
s

0    80000
1    90000
dtype: object

# 시리즈 인덱스

In [181]:
data = [1000, 2000, 3000]
s = pd.Series(data)
print(type(s.index)) # pandas에서 사용하는 객체

<class 'pandas.core.indexes.range.RangeIndex'>


In [182]:
list(s.index)

[0, 1, 2]

In [183]:
s.index.to_list()

[0, 1, 2]

In [199]:
#help(s.index) # 클래스에는 항상 속성과 메서드가 존재한다. 
# 원하는 메소드가 있으면, type 찾아보고 RangeIndex -> 공식문서 검색, to_list() 없으면 상위 클래스에서 상속 된거라 생각하고 한단계씩 올라가기

In [243]:
# 시리즈 생성하면서 인덱스도 같이 생성
data = [1000, 2000, 3000,]
index = ["메로나", "월드콘", "와"]

s = pd.Series(data=data, index=index) # data, index 명 지정해서 생성 가능
s

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [209]:
s.values, type(s.values) # numpy 배열임

(array([1000, 2000, 3000]), numpy.ndarray)

In [210]:
s.index

Index(['메로나', '월드콘', '와'], dtype='object')

# 시리즈 인덱싱

In [215]:
print(s.iloc[0]), print(s.iloc[1]), print(s.iloc[2]) # 위치 index를 입력해서 값을

1000
2000
3000


(None, None, None)

In [212]:
print(s.loc["메로나"]) # 값 index를 입력해서 값을 가져옴

1000


In [216]:
data = [1000, 2000, 3000,]
# index가 없음
s2 = pd.Series(data=data)
s2.index.to_list()

[0, 1, 2]

In [217]:
print(s2.iloc[0]) # iloc에서는 0은 위치 0을 의미
print(s2.loc[0]) # loc에서의 0은 라벨 0을 미미

1000
1000


In [227]:
print(s.loc["메로나"])
print(s.loc[["메로나", "와", "월드콘"]]) # 여러개 불러올 때는 []로 묶어서 가져옴 

1000
메로나    1000
와      3000
월드콘    2000
dtype: int64


# 슬라이싱

In [229]:
s.iloc[0:2]

메로나    1000
월드콘    2000
dtype: int64

In [231]:
s.loc["메로나":"와"]

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [233]:
s2.iloc[0:2]

0    1000
1    2000
dtype: int64

In [234]:
s2.loc[0:2]

0    1000
1    2000
2    3000
dtype: int64

## 시리즈 수정/추가/삭제

In [268]:
# 시리즈 생성하면서 인덱스도 같이 생성
data = [1000, 2000, 3000,]
index = ["메로나", "월드콘", "와"]

s = pd.Series(data=data, index=index) # data, index 명 지정해서 생성 가능
s

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [240]:
s.loc["메로나"] = 500 # 수정 방법 1 Dic key값으로 value 값 수정하는 것과 유사함
s

메로나     500
월드콘    2000
와      3000
dtype: int64

In [244]:
s.iloc[0] = 500 # 수정 방법 2
s

메로나     500
월드콘    2000
와      3000
dtype: int64

In [246]:
s['메로나'] = 500 # 수정 방법 3
s

메로나     500
월드콘    2000
와      3000
dtype: int64

In [267]:
s.drop(labels = ['메로나',"와"]) # 삭제 하는 법

월드콘    2000
dtype: int64

# 시리즈 연산
- index 값 매칭을 통해 동일한 index를 찾아가서 연산을 해줌
- 시리즈끼리 바로 연산 가능함 (a + b, a - b...)

In [254]:
import pandas as pd

evan = pd.Series([10, 20, 300], index=["naver", "apple", "nvieda"])
딸1 = pd.Series([10, 30, 20], index=["nvieda", "naver", "apple"])

evan

naver      10
apple      20
nvieda    300
dtype: int64

In [255]:
딸1

nvieda    10
naver     30
apple     20
dtype: int64

In [256]:
evan + 딸1

apple      40
naver      40
nvieda    310
dtype: int64

In [258]:
import pandas as pd 

evan = pd.Series([10, 20, 300], index=["naver", "apple", "tesla"])
딸1 = pd.Series([10, 30, 20], index=["nvieda", "naver", "apple"])

evan # 각 Series의 index가 맞지 않은 상태에서 더하면 NaN 발생함

naver     10
apple     20
tesla    300
dtype: int64

In [259]:
딸1

nvieda    10
naver     30
apple     20
dtype: int64

In [260]:
evan + 딸1

apple     40.0
naver     40.0
nvieda     NaN
tesla      NaN
dtype: float64

In [270]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = pd.Series([42800, 42700, 42050, 42950, 43000], index=date)
low = pd.Series([42150, 42150, 41300, 42150, 42350] , index=date)

diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [275]:
diff.idxmax(), diff[diff.idxmax()] # 최대값의 ID, 값

('6/4', np.int64(800))

In [276]:
diff.idxmin() # 최소값의 ID, 값

'6/2'

In [277]:
profit = high / low # 단순 수익률 계산
profit

6/1    1.015421
6/2    1.013049
6/3    1.018160
6/4    1.018980
6/5    1.015348
dtype: float64

In [280]:
profit.cumprod() # 누적곱

6/1    1.015421
6/2    1.028671
6/3    1.047351
6/4    1.067230
6/5    1.083610
dtype: float64

# 시리즈와 Map

In [282]:
s = pd.Series(['1,234', '5,678', '12,345'])
int(s) # 문자 -> 숫자로 바로 변경 안됨 

TypeError: cannot convert the series to <class 'int'>

In [285]:
text = '1,234'
result = int(text.replace(",",""))
type(result), result

(int, 1234)

In [287]:
num_str = ['1,234', '5,678', '12,345']
results = []
for num in num_str:
    temp = int(num.replace(",",""))
    results.append(temp)

results

[1234, 5678, 12345]

In [291]:
def rm_comma(x):
    return int(x.replace(",",""))

In [292]:
s = pd.Series(['1,234', '5,678', '12,345'])
result = s.map(rm_comma) # map 함수는 사용자지정 함수를 쓸 수 있게 해주는 함수이며, 사용자 지정함수를 만들어줘야함
result

0     1234
1     5678
2    12345
dtype: int64

In [294]:
def remove_dollar_sign(x):
    return float(x.replace('$', '').replace(',', '')) # 함수 연속 사용 확인
s = pd.Series(['$1,234.56', '$5,678.90', '$12,345.67'])
result = s.map(remove_dollar_sign)
result

0     1234.56
1     5678.90
2    12345.67
dtype: float64

# 문제
- 기준점이 13이상
  + 크다 or 작다

In [303]:
s = pd.Series([5, 10, 15, 20])
s

0     5
1    10
2    15
3    20
dtype: int64

In [306]:
def ud(x):
    if x >= 13 :
        return "크다"
    else:
        return "작다"
        
result = s.map(ud)
result

In [309]:
result = s.map(lambda x: '크다' if x>=13 else '작다') # lambda 사용하여 한문장 처리, pandas에서 많이 사용함
result

0    작다
1    작다
2    크다
3    크다
dtype: object

In [313]:
result = s.apply(lambda x: '크다' if x>=13 else '작다') # map과 비슷한 기능을 함 apply
result

0    작다
1    작다
2    크다
3    크다
dtype: object

## 필터링

In [315]:
data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = pd.Series(data=data, index=index)
s

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [316]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [317]:
s[cond]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [318]:
s[s > 42000]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [322]:
from pandas import Series

close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open = Series(data=open, index=index)
close = Series(data=close, index=index)

# 문제: 종가가 시가보다 높은 날을 구하세요

In [350]:
gap = close - open
gap[gap > 0].index

Index(['2019-05-30', '2019-05-27'], dtype='object')