## 문제 1. 
문제: 모든 값이 0으로 2차원 배열 (5, 5) 만드세요. 

In [30]:
import numpy as np

arr1 = np.zeros(25).reshape(5,5)
arrr = np.zeros((5,5)) #안에 튜플 값으로 넣으면 배열 된다 
print(arr1)
print(arrr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 문제 2. 
임의의 3x3 크기의 배열을 생성하고 배열의 shape(모양), dtype(데이터 타입), 그리고 배열의 차원 수(ndim)를 출력하세요.

In [33]:

arr2 = np.arange(9).reshape(3, 3)
arr2, arr2.shape, arr2.dtype, arr2.ndim
 

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 (3, 3),
 dtype('int64'),
 2)

## 문제 3. 
- 주어진 배열에서 아래와 같이 슬라이싱 하세요. 
```
array([[ 5,  6],
       [ 9, 10]])
```

In [24]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
arr[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])